from register import Register

notes = [
  # ('bamm.mp4', 'bamm'),
  # ('boom.mp4', 'boom'),
  # ('chak.mp4', 'chak'),
  # ('a3.MOV', 'a3'),
  # ('a3s.MOV', 'as3'),
  # ('b3.MOV', 'b3'),
  # ('c3.MOV', 'c3'),
  # ('cs3.MOV', 'cs3'),
  # ('c4.MOV', 'c4'),
  # ('d3.MOV', 'd3'),
  # ('ds3.MOV', 'ds3'),
  # ('e3.MOV', 'e3'),
  # ('f3.MOV', 'f3'),
  # ('fs3.MOV', 'fs3'),
  # ('g3.MOV', 'g3'),
  # ('gs3.MOV', 'gs3'),
  # ('a2.mp4', 'a2'),
  # ('c2.mp4', 'c2'),
  # ('d2.mp4', 'd2'),
  # ('e2.mp4', 'e2'),
  # ('f2.mp4', 'f2'),
  # ('g2.mp4', 'g2'),
  # ('ds2.mp4', 'ds2'),
  # ('as3d4.mp4', 'as3d4'),
    # ('g3c4.mp4', 'g3c4'),
    # ('g3as3.mp4', 'g3as3'),
  # ('fs2.mp4', 'fs2'),
    # ('flowerpot.mp4', 'flowerpot'),
    # ('flowerpot_re.mp4', 'flowerpot'),
    # ('triangle.mp4', 'triangle'),
    # ('triangle_re.mp4', 'triangle'),
    # ('cleartong1.mp4','cleartong1'),
    # ('cleartong2.mp4','cleartong2'),
    # ('highding.mp4','highding'),
    # ('hightong.mp4','hightong'),
    # ('highding.mp4','highding'),
    # ('lowding.mp4','lowding'),
    # ('lowkung.mp4','lowkung'),
    # ('lowtuk.mp4','lowtuk'),
    # ('midtong.mp4','midtong'),
    # ('midtuk1.mp4','midtuk1'),
    # ('midtuk2.mp4','midtuk2'),
    # ('midtung.mp4','midtung'),
    # ('c5.mp4','c5'),
    # ('cs5.mp4','cs5'),
    # ('d5.mp4','d5'),
    # ('ds5.mp4','ds5'),
    # ('e5.mp4','e5'),
    # ('f5.mp4','f5'),
    # ('fs5.mp4','fs5'),
    # ('g5.mp4','g5'),
    # ('a5.mp4','a5'),
    # ('as5.mp4','as5'),
    # ('.mp4',''),
    # ('.mp4',''),
    # ('.mp4',''),
    # ('.mp4',''),
    # ('.mp4',''),
    # ('.mp4',''),
    # ('.mp4',''),
    # ('.mp4',''),
    # ('.mp4',''),
    # ('.mp4',''),
    # ('.mp4',''),
    # ('.mp4',''),
    # ('.mp4',''),
    # ('.mp4',''),
    # ('.mp4',''),
    # ('.mp4',''),
    # ('.mp4',''),
    # ('.mp4',''),
    # ('.mp4',''),
    # ('.mp4',''),
]

for n in notes:
    Register('./origin_note/'+n[0], n[1])
    print(n[0] + ' is registered as ' + n[1])
